apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker 
  name: 100-worker-blacklist 
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
      - modprobe.blacklist=ixgbevf
      - intel_iommu=on
      - hugepages=1024
