apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  additionalKernelArgs:
  - intel_iommu=on
  - modprobe.blacklist=ixgbevf
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - count: 2
        node: 0
        size: 1G  
  cpu: {}
  nodeSelector:
    node-role.kubernetes.io/worker: ""
