apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: sriovdp
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed", "1889"],
                    "drivers": ["vfio-pci"]
                }
            }
        ]
    }
